typedef enum GameScreen
{
    SCREEN_NOVO_JOGO,
    SCREEN_CONTINUAR,
    SCREEN_RANKING,
    SCREEN_COMO_JOGAR,
    SCREEN_FECHAR_JOGO,
    SCREEN_MENU,
    SCREEN_RUNNING,
    SCREEN_SAVE_GAME,
    SCREEN_LOAD_GAME,
    SCREEN_EXIT_GAME,
    SCREEN_LEVEL_FINISHED,
    SCREEN_GAME_OVER,
    SCREEN_WINNER,
} GameScreen;

typedef enum GameState
{
    GAME_TIMEOUT,
    GAME_LEVEL_FINISHED,
    GAME_PAUSE,
} GameState;