typedef enum GameScreen
{
    SCREEN_NOVO_JOGO,
    SCREEN_CONTINUAR,
    SCREEN_RANKING,
    SCREEN_COMO_JOGAR,
    SCREEN_FECHAR_JOGO,
    SCREEN_MENU,
    SCREEN_SAVE_GAME,
    SCREEN_LOAD_GAME,
    SCREEN_EXIT_GAME,
} GameScreen;
